# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='Proto',
  syntax='proto2',
  serialized_pb=_b('\n\ngame.proto\x12\x05Proto\"+\n\rC2S_AcctLogin\x12\x0c\n\x04\x61\x63\x63t\x18\x01 \x01(\t\x12\x0c\n\x04zone\x18\x02 \x01(\r\"E\n\rS2C_AcctLogin\x12 \n\x04\x63ode\x18\x01 \x01(\x0e\x32\x12.Proto.GameErrcode\x12\x12\n\nisTempAcct\x18\x03 \x01(\r*&\n\x0bGameErrcode\x12\n\n\x06GEC_OK\x10\x00\x12\x0b\n\x07GEC_Err\x10\x01')
)

_GAMEERRCODE = _descriptor.EnumDescriptor(
  name='GameErrcode',
  full_name='Proto.GameErrcode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GEC_OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEC_Err', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=137,
  serialized_end=175,
)
_sym_db.RegisterEnumDescriptor(_GAMEERRCODE)

GameErrcode = enum_type_wrapper.EnumTypeWrapper(_GAMEERRCODE)
GEC_OK = 0
GEC_Err = 1



_C2S_ACCTLOGIN = _descriptor.Descriptor(
  name='C2S_AcctLogin',
  full_name='Proto.C2S_AcctLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='acct', full_name='Proto.C2S_AcctLogin.acct', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='zone', full_name='Proto.C2S_AcctLogin.zone', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=64,
)


_S2C_ACCTLOGIN = _descriptor.Descriptor(
  name='S2C_AcctLogin',
  full_name='Proto.S2C_AcctLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='Proto.S2C_AcctLogin.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isTempAcct', full_name='Proto.S2C_AcctLogin.isTempAcct', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=135,
)

_S2C_ACCTLOGIN.fields_by_name['code'].enum_type = _GAMEERRCODE
DESCRIPTOR.message_types_by_name['C2S_AcctLogin'] = _C2S_ACCTLOGIN
DESCRIPTOR.message_types_by_name['S2C_AcctLogin'] = _S2C_ACCTLOGIN
DESCRIPTOR.enum_types_by_name['GameErrcode'] = _GAMEERRCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

C2S_AcctLogin = _reflection.GeneratedProtocolMessageType('C2S_AcctLogin', (_message.Message,), dict(
  DESCRIPTOR = _C2S_ACCTLOGIN,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:Proto.C2S_AcctLogin)
  ))
_sym_db.RegisterMessage(C2S_AcctLogin)

S2C_AcctLogin = _reflection.GeneratedProtocolMessageType('S2C_AcctLogin', (_message.Message,), dict(
  DESCRIPTOR = _S2C_ACCTLOGIN,
  __module__ = 'game_pb2'
  # @@protoc_insertion_point(class_scope:Proto.S2C_AcctLogin)
  ))
_sym_db.RegisterMessage(S2C_AcctLogin)


# @@protoc_insertion_point(module_scope)
